FROM amazon/aws-lambda-nodejs:14

RUN yum update -y && yum install -y amazon-linux-extras

RUN amazon-linux-extras install epel -y && yum install -y chromium

COPY . .

RUN npm install && node node_modules/puppeteer-core/install.js && npm run build

EXPOSE 3000

CMD ["dist/handlers/scraper-handler.scraperHandler"]