service: lq-scraper

provider: 
  name: aws
  runtime: nodejs14.x
  stage: dev1
  region: us-east-2

plugins:
  - serverless-webpack

package:
  exclude:
    - ./**
  include:
    - package.json
    - src/**

functions:
  ScrapHandler:
    handler: src/handlers/scraper-handler.scraperHandler
    timeout: 900
    memorySize: 1024

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true