service: linkedin-scraper

package:
  exclude:
    - src/**
    - ref-data/**

provider: 
  name: aws
  runtime: nodejs12.x
  memorySize: 512 
  timeout: 15
  stage: test
  region: us-east-2

functions:
  api:
    handler: dist/lambda.universal
    events: 
      - http: ANY {proxy+}
      - http: ANY /