service: lc

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-webpack

package:
  include:
    - src/**/*
    - reference-data/*
  exclude:
    - node_modules/**/*
    - .serverless/**/*
    - .vscode/**/*

functions:
  ### Reference Data
  get-refdata:
    handler: src/controllers/refdata-controller.getRefData
    events:
      - http:
          method: get
          path: api/v1/refdata

  reset-refdata:
    handler: src/controllers/refdata-controller.resetRefData
    events:
      - http:
          method: get
          path: api/v1/refdata/reset

  ### Auth
  get-access-token:
    handler: src/controllers/auth-controller.getAccessToken
    events:
      - http:
          method: get
          path: api/v1/auth/linkedinAccessToken

  # sign-in:
  #   handler: src/controllers/auth-controller.signIn
  #   events:
  #     - http:
  #         method: post
  #         path: api/v1/auth/login

  # sign-up:
  #   handler: src/controllers/auth-controller.signUp
  #   events:
  #     - http:
  #         method: post
  #         path: api/v1/auth/register

  ### User
  get-user:
    handler: src/controllers/user-controller.getUserById
    events:
      - http:
          method: get
          path: api/v1/user/{userId}
  update-user:
    handler: src/controllers/user-controller.updateUserById
    events:
      - http:
          method: put
          path: api/v1/user/{userId}
  create-user:
    handler: src/controllers/user-controller.createUser
    events:
      - http:
          method: post
          path: api/v1/user/new

  ### Team
  get-team:
    handler: src/controllers/team-controller.getTeamById
    events:
      - http:
          method: get
          path: api/v1/team/{teamId}
  update-team:
    handler: src/controllers/team-controller.updateTeamById
    events:
      - http:
          method: put
          path: api/v1/team/{teamId}
  create-team:
    handler: src/controllers/team-controller.createTeam
    events:
      - http:
          method: post
          path: api/v1/team/new

  ### Customer
  get-customer: 
    handler: src/controllers/customer-controller.getCustomerById
    events:
      - http:
          method: get
          path: api/v1/customer/single/{customerId}
  update-customer: 
    handler: src/controllers/customer-controller.updateCustomerById
    events:
      - http:
          method: put
          path: api/v1/customer/single/{customerId}
  create-customer: 
    handler: src/controllers/customer-controller.createCustomer
    events:
      - http:
          method: post
          path: api/v1/customer/single/new
  get-customers-list: 
    handler: src/controllers/customer-controller.getCustomersListByIds
    events:
      - http:
          method: get
          path: api/v1/customer/list/{customerIds}
  create-customers-list: 
    handler: src/controllers/customer-controller.createCustomersList
    events:
      - http:
          method: post
          path: api/v1/customer/list/new

  ### Campaign
  get-campaign:
    handler: src/controllers/campaign-controller.getCampaignById
    events:
      - http:
          method: get
          path: api/v1/campaign/{campaignId}
  update-campaign:
    handler: src/controllers/campaign-controller.updateCampaignById
    events:
      - http:
          method: put
          path: api/v1/campaign/{campaignId}
  post-campaign:
    handler: src/controllers/campaign-controller.createCampaign
    events:
      - http:
          method: post
          path: api/v1/campaign/new
  change-pipeline-stage:
    handler: src/controllers/campaign-controller.changePipelineStage
    events:
      - http:
          method: put
          path: api/v1/campaign/pipeline/stageChange

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

  